# EventMonitor設定ファイル

# 監視対象アカウント（monitored_accounts.csvから読み込み）


# LLMモデル設定（フォールバック順）
models:
  - "gemini-2.0-flash"       # 第1優先
  - "gemini-2.5-flash"       # 第2優先
  - "gemini-2.5-pro"         # 第3優先
  - "gpt-4o"                 # 第4優先
# データベース設定
# SQLiteを使用
database:
  type: "sqlite"
  path: "data/eventmonitor.db"

# Discord通知設定
discord:
  # 通知内容の設定
  notification:
    mention_role: null  # @everyone, @here, または特定のロールID
    embed_color: 0x1da1f2  # Twitter青

# ツイート取得設定
tweet_settings:
  # 過去何日分のツイートを取得するか
  days_lookback: 36500  # 1=1日
  # リトライ設定
  max_retries: 3
  retry_delay: 60  # 秒
  
  # gallery-dl設定（メディア付きツイートの取得と画像・動画ダウンロード）
  gallery_dl:
    # gallery-dlを使用するか（優先実行される）
    enabled: true
    # 強制的に全ツイートを取得するか（新着チェックをスキップ）
    force_full_fetch: false
    # 一度にダウンロードする最大ツイート数（大量の場合は分割）
    max_batch_size: 100
  
  # twscrape設定（テキストのみツイート取得）
  twscrape:
    # twscrapeを使用するか（gallery-dlで取得できなかったツイートを補完）
    enabled: true
    # 強制的に全ツイートを取得するか（効率化を無視）
    force_full_fetch: false
  
  # 鍵アカウント用の指定Cookie設定
  private_account_cookies:
    # gallery-dl用の指定Cookieファイル（鍵アカウントでリトライ時に使用）
    gallery_dl_cookie: "cookies/x.com_cookies.txt"
    # twscrape用の指定アカウント（.envのTWITTER_ACCOUNT_番号）
    twscrape_account: 1

# イベント判定設定
event_detection:
  # イベント検出機能を有効にするか（false: クローラーとしてのみ動作）
  enabled: true
  # イベント関連キーワード
  keywords:
    - "参加"
    - "出展"
    - "ブース"
    - "スペース"
    - "サークル"
    - "新刊"
    - "頒布"
    - "委託"
    - "イベント"
    - "コミケ"
    - "C102"
    - "C103"
    - "コミティア"
    - "M3"
    - "例大祭"
    - "オンリー"
    - "通販"
    - "BOOTH"
    - "メロンブックス"
    - "とらのあな"

  # 除外キーワード（これらが含まれる場合は通知しない）
  exclude_keywords:
    - "完売"
    - "終了"

# 画像管理設定
image_settings:
  # 古い画像の自動削除を有効にするか
  cleanup_enabled: false
  # 画像保持期間（日数）
  retention_days: 30

# Hugging Faceバックアップ設定
huggingface_backup:
  # バックアップを有効にするか
  enabled: false
  # リポジトリ名（config.yamlで設定）
  repo_name: "Sageen/EventMonitor_1"
  # 画像も含めるか
  include_images: true
  # アップロードモード ('immediate': 即時アップロード, 'batch': 全ダウンロード後一括アップロード)
  upload_mode: 'immediate'
  # rclone暗号化設定
  rclone_encryption:
    # 暗号化を有効にするか
    enabled: false
    # rclone設定ファイルのパス（省略時はデフォルトのrclone.conf）
    config_path: "rclone.conf"
  # レート制限時の待機をスキップするか（falseで適切に待機）
  skip_rate_limit_wait: false


# Hydrus Client連携設定
hydrus:
  # 連携を有効にするか
  enabled: true
  # Hydrus Client APIのURL
  api_url: "http://127.0.0.1:45869"
  # インポート設定
  import_settings:
    # イベント関連ツイートのみインポートするか
    event_tweets_only: false
    # 既存ファイルのスキップ（SHA256ハッシュで判定）
    skip_existing: true
  # タグ設定
  tag_settings:
    # 基本タグ（必ず付与）
    base_tags:
      - "source:twitter"
      - "imported_by:eventmonitor"
    # クリエイター名のタグ形式
    creator_tag_format: "creator:{name}"
    # イベント名のタグ形式
    event_tag_format: "event:{name}"
    # 日付タグを追加するか（デフォルト: false）
    include_date_tag: false
    # 日付タグの形式
    # date_tag_format: "date:{date}"
    # ツイートURLをタグとして追加するか（デフォルト: false）
    include_tweet_url: false
    # タイトルタグ（ツイート本文）を追加するか（デフォルト: true）
    include_title_tag: true
    # 検出されたキーワードをタグとして追加するか
    # include_detected_keywords: true

# システム設定
system:
  # ログレベル (DEBUG, INFO, WARNING, ERROR)
  log_level: "DEBUG"
  # データ保存ディレクトリ
  data_dir: "data"
  # 実行間隔（分）
  check_interval: 60

# メディア保存設定
media_storage:
  # 画像ファイルの保存パス（例: "/mnt/f/Crawler/images"）
  images_path: "images"
  # 動画ファイルの保存パス（例: "/mnt/f/Crawler/videos"）
  videos_path: "videos"

# ログ専用アカウント設定
log_only_accounts:
  # 機能を有効にするか
  enabled: true
  # アップロード後に画像を即削除するか
  delete_after_upload: true
  # 一度に処理するツイート数
  batch_size: 50
  # アップロードモード ('immediate': 即時アップロード, 'batch': 全ダウンロード後一括アップロード)
  upload_mode: 'immediate'
  # バッチモード用設定
  batch_mode:
    # 暗号化を有効にするか（logアカウントのみ）
    encrypt_before_upload: false
    # アップロード後にフォルダを削除するか
    delete_after_batch_upload: false
